### ISSUE TITLE
merge into main plugin

### ISSUE THREAD

**Issue by zebapy** [leonardodino/gatsby-plugin-page-creator#1]
Has there been talk of merging this feature into the official plugin? Seems very important to have this unless you want to set up `gatsby-node.js` boilerplate page creation..

**Comment by leonardodino** [comment]
see previous discussion here: https://github.com/gatsbyjs/gatsby/pull/10960
this repo is just a fork adding the 2 options (`createPath` + `validatePath`).

the main `gatsby-plugin-page-creator` lives in the [gatsby repo](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-page-creator) and can be installed with regular commands.
